### ISSUE TITLE
Handbook cannot be opened : uses an unsupported protocol

### ISSUE THREAD

**Issue by vigfusg** [island-is/handbook#37]
Go to: https://island.is/throun/handbok
Press link: Þróunarhandbók á gitbook

Browser: Chrome 89.0.4389.114 (Official Build) (64-bit)
![Unsupported protocol](https://user-images.githubusercontent.com/4609048/113706993-cf488d80-96ce-11eb-986e-74c8a4fa962c.PNG)

**Comment by AndriMar** [comment]
Related or duplicate https://github.com/island-is/infrastructure/issues/645

**Comment by sindrig** [comment]
Fixed by updating configuration in gitbook.com
This closes island-is/infrastructure#645
